name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: make directories
        run: |
          mkdir -p /root/ros2_ws2/src/mypkg
      - name: build and test
      - run: |
          rsync -av ./ /root/ros2_ws2/src/mypkg/
          cd /root/ros2_ws2
          bash -xv ./src/mypkg/test/test.bash /root
